#include "buzzer.h"

enum NoteFreq : uint16_t
{
    REST = 0,
    B0 = 31,
    C1 = 33,
    CS1 = 35,
    D1 = 37,
    DS1 = 39,
    E1 = 41,
    F1 = 44,
    FS1 = 46,
    G1 = 49,
    GS1 = 52,
    A1 = 55,
    AS1 = 58,
    B1 = 62,
    C2 = 65,
    CS2 = 69,
    D2 = 73,
    DS2 = 78,
    E2 = 82,
    F2 = 87,
    FS2 = 93,
    G2 = 98,
    GS2 = 104,
    A2 = 110,
    AS2 = 117,
    B2 = 123,
    C3 = 131,
    CS3 = 139,
    D3 = 147,
    DS3 = 156,
    E3 = 165,
    F3 = 175,
    FS3 = 185,
    G3 = 196,
    GS3 = 208,
    A3 = 220,
    AS3 = 233,
    B3 = 247,
    C4 = 262,
    CS4 = 277,
    D4 = 294,
    DS4 = 311,
    E4 = 330,
    F4 = 349,
    FS4 = 370,
    G4 = 392,
    GS4 = 415,
    A4 = 440,
    AS4 = 466,
    B4 = 494,
    C5 = 523,
    CS5 = 554,
    D5 = 587,
    DS5 = 622,
    E5 = 659,
    F5 = 698,
    FS5 = 740,
    G5 = 784,
    GS5 = 831,
    A5 = 880,
    AS5 = 932,
    B5 = 988,
    C6 = 1047,
    CS6 = 1109,
    D6 = 1175,
    DS6 = 1245,
    E6 = 1319,
    F6 = 1397,
    FS6 = 1480,
    G6 = 1568,
    GS6 = 1661,
    A6 = 1760,
    AS6 = 1865,
    B6 = 1976,
    C7 = 2093,
    CS7 = 2217,
    D7 = 2349,
    DS7 = 2489,
    E7 = 2637,
    F7 = 2794,
    FS7 = 2960,
    G7 = 3136,
    GS7 = 3322,
    A7 = 3520,
    AS7 = 3729,
    B7 = 3951,
    C8 = 4186,
    CS8 = 4435,
    D8 = 4699,
    DS8 = 4978
};

constexpr Note NoNotes[] = {
    // A long pause with no sound. A slightly hacky way to make the alarm not deactivate instantly when set.
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 1},
    {NoteFreq::REST, 0}};
constexpr Melody NoMelody = {NoNotes, 180};

constexpr Note Beep[] = {
    // A single long tone
    {NoteFreq::D5, 1},
    {NoteFreq::REST, 16},
    {NoteFreq::REST, 0}};
constexpr Melody BeepMelody = {Beep, 180};

constexpr Note Breeze[] = {
    // Breezy wind gust-y tone
    {NoteFreq::GS4, 16},
    {NoteFreq::A4, 16},
    {NoteFreq::AS4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::C5, 16},
    {NoteFreq::CS5, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::DS5, 16},
    {NoteFreq::E5, 16},
    {NoteFreq::F5, 16},
    {NoteFreq::FS5, 16},
    {NoteFreq::G5, 16},
    {NoteFreq::GS5, 16},
    {NoteFreq::A5, 16},
    {NoteFreq::AS5, 16},
    {NoteFreq::AS5, 16},
    {NoteFreq::A5, 16},
    {NoteFreq::GS5, 16},
    {NoteFreq::G5, 16},
    {NoteFreq::FS5, 16},
    {NoteFreq::F5, 16},
    {NoteFreq::E5, 16},
    {NoteFreq::DS5, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::CS5, 16},
    {NoteFreq::C5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::AS4, 16},
    {NoteFreq::A4, 16},
    {NoteFreq::GS4, 16},
    {NoteFreq::G4, 16},
    {NoteFreq::FS4, 16},
    {NoteFreq::F4, 16},
    {NoteFreq::E4, 16},
    {NoteFreq::DS4, 16},
    {NoteFreq::D4, 16},
    {NoteFreq::CS4, 16},
    {NoteFreq::C4, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::AS3, 16},
    {NoteFreq::A3, 16},
    {NoteFreq::GS3, 16},
    {NoteFreq::G3, 16},
    {NoteFreq::FS3, 16},
    {NoteFreq::F3, 16},
    {NoteFreq::REST, 0}};
constexpr Melody BreezeMelody = {Breeze, 420};

constexpr Note Rumble[] = {
    // A low pitch rumbling tone
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::E2, 16},
    {NoteFreq::REST, 32},
    {NoteFreq::REST, 0}};
constexpr Melody RumbleMelody = {Rumble, 240};

constexpr Note Bzzz[] = {
    // A mid pitch fast rumbling tone
    {NoteFreq::B3, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::B3, 16},
    {NoteFreq::REST, 0}};
constexpr Melody BzzzMelody = {Bzzz, 240};

constexpr Note DoomNotes[] = {
    // At Doom's Gate (E1M1)
    // Score available at https://musescore.com/pieridot/doom
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::B2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, -2},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::B2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, -2},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::B2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, -2},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::B2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::FS3, -16},
    {NoteFreq::D3, -16},
    {NoteFreq::B2, -16},
    {NoteFreq::A3, -16},
    {NoteFreq::FS3, -16},
    {NoteFreq::B2, -16},
    {NoteFreq::D3, -16},
    {NoteFreq::FS3, -16},
    {NoteFreq::A3, -16},
    {NoteFreq::FS3, -16},
    {NoteFreq::D3, -16},
    {NoteFreq::B2, -16},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::B2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, -2},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::AS2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::B2, 8},
    {NoteFreq::C3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::D3, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::E2, 8},
    {NoteFreq::B3, -16},
    {NoteFreq::G3, -16},
    {NoteFreq::E3, -16},
    {NoteFreq::G3, -16},
    {NoteFreq::B3, -16},
    {NoteFreq::E4, -16},
    {NoteFreq::G3, -16},
    {NoteFreq::B3, -16},
    {NoteFreq::E4, -16},
    {NoteFreq::B3, -16},
    {NoteFreq::G4, -16},
    {NoteFreq::B4, -16},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::G3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::F3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::DS3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::F3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::G3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::F3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::DS3, -2},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::G3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::F3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::DS3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::E3, 8},
    {NoteFreq::F3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::G3, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A2, 8},
    {NoteFreq::A3, -16},
    {NoteFreq::F3, -16},
    {NoteFreq::D3, -16},
    {NoteFreq::A3, -16},
    {NoteFreq::F3, -16},
    {NoteFreq::D3, -16},
    {NoteFreq::C4, -16},
    {NoteFreq::A3, -16},
    {NoteFreq::F3, -16},
    {NoteFreq::A3, -16},
    {NoteFreq::F3, -16},
    {NoteFreq::D3, 16},
    {NoteFreq::REST, 0}};
constexpr Melody DoomMelody = {DoomNotes, 225};

constexpr Note RickRollNotes[] = {
    // Never Gonna Give You Up - Rick Astley
    // Score available at https://musescore.com/chlorondria_5/never-gonna-give-you-up_alto-sax
    // Arranged by Chlorondria
    {NoteFreq::D5, -4},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 4},
    {NoteFreq::E5, -4},
    {NoteFreq::FS5, -4},
    {NoteFreq::A5, 16},
    {NoteFreq::G5, 16},
    {NoteFreq::FS5, 8},
    {NoteFreq::D5, -4},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 2},
    {NoteFreq::A4, 16},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 8},
    {NoteFreq::D5, 16},
    {NoteFreq::D5, -4},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 4},
    {NoteFreq::E5, -4},
    {NoteFreq::FS5, -4},
    {NoteFreq::A5, 16},
    {NoteFreq::G5, 16},
    {NoteFreq::FS5, 8},
    {NoteFreq::D5, -4},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 2},
    {NoteFreq::A4, 16},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 8},
    {NoteFreq::D5, 16},
    {NoteFreq::REST, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::CS5, -8},
    {NoteFreq::B4, 16},
    {NoteFreq::A4, 2},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::E5, -4},
    {NoteFreq::REST, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, -4},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::REST, 4},
    {NoteFreq::D5, 2},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::A4, 4},
    {NoteFreq::REST, 2},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::FS5, -8},
    {NoteFreq::FS5, -8},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::E5, -8},
    {NoteFreq::E5, -8},
    {NoteFreq::D5, -8},
    {NoteFreq::CS5, 16},
    {NoteFreq::B4, -8},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::CS5, -8},
    {NoteFreq::B4, 16},
    {NoteFreq::A4, 8},
    {NoteFreq::A4, 8},
    {NoteFreq::A4, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::D5, 2},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::FS5, -8},
    {NoteFreq::FS5, -8},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::A5, 4},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, -8},
    {NoteFreq::CS5, 16},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::CS5, -8},
    {NoteFreq::B4, 16},
    {NoteFreq::A4, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::D5, 2},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, -4},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::A4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, -4},
    {NoteFreq::REST, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 4},
    {NoteFreq::E5, -4},
    {NoteFreq::D5, 2},
    {NoteFreq::D5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::A4, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::REST, -4},
    {NoteFreq::A4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::FS5, -8},
    {NoteFreq::FS5, -8},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::E5, -8},
    {NoteFreq::E5, -8},
    {NoteFreq::D5, -8},
    {NoteFreq::CS5, 16},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::CS5, -8},
    {NoteFreq::B4, 16},
    {NoteFreq::A4, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::D5, 2},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::FS5, -8},
    {NoteFreq::FS5, -8},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::A5, 4},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, -8},
    {NoteFreq::CS5, 16},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::CS5, -8},
    {NoteFreq::B4, 16},
    {NoteFreq::A4, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::D5, 2},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::FS5, -8},
    {NoteFreq::FS5, -8},
    {NoteFreq::E5, -4},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::A5, 4},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, -8},
    {NoteFreq::CS5, 16},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 16},
    {NoteFreq::B4, 16},
    {NoteFreq::D5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::CS5, -8},
    {NoteFreq::B4, 16},
    {NoteFreq::A4, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::E5, 4},
    {NoteFreq::D5, 2},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 0}};
constexpr Melody RickRollMelody = {RickRollNotes, 114};

constexpr Note NokiaRingtone[] = {
    // Nokia Ringtone
    // Score available at https://musescore.com/user/29944637/scores/5266155
    {NoteFreq::E5, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::FS4, 4},
    {NoteFreq::GS4, 4},
    {NoteFreq::CS5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::D4, 4},
    {NoteFreq::E4, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 8},
    {NoteFreq::CS4, 4},
    {NoteFreq::E4, 4},
    {NoteFreq::A4, 2},
    {NoteFreq::REST, 0}};
constexpr Melody NokiaMelody = {NokiaRingtone, 180};

constexpr Note KrabNotes[] = {
    // Krusty Krab theme from Spongebob
    // https://musescore.com/user/7040741/scores/2683921
    {NoteFreq::D5, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::C5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::G4, 8},
    {NoteFreq::D4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 4},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::FS4, 4},
    {NoteFreq::E4, 8},
    {NoteFreq::FS4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::C5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 4},
    {NoteFreq::D5, 8},
    {NoteFreq::C5, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::G4, 8},
    {NoteFreq::D4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 4},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::C5, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::G5, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::C5, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::G4, 4},
    {NoteFreq::G4, 4},
    {NoteFreq::FS4, 2},
    {NoteFreq::G4, 8},
    {NoteFreq::D5, 8},
    {NoteFreq::CS5, 8},
    {NoteFreq::C5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::G4, 8},
    {NoteFreq::D4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 4},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::FS4, 4},
    {NoteFreq::E4, 8},
    {NoteFreq::FS4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::C5, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::A4, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::CS5, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::E5, 8},
    {NoteFreq::FS5, 4},
    {NoteFreq::D5, 8},
    {NoteFreq::C5, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::G4, 8},
    {NoteFreq::D4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::B4, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::A5, 8},
    {NoteFreq::G5, 8},
    {NoteFreq::FS5, 8},
    {NoteFreq::G5, 4},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, 4},
    {NoteFreq::G4, 8},
    {NoteFreq::B4, 8},
    {NoteFreq::C5, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::G5, 8},
    {NoteFreq::D5, 4},
    {NoteFreq::C5, 8},
    {NoteFreq::A4, 4},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, 4},
    {NoteFreq::A4, 8},
    {NoteFreq::G4, 4},
    {NoteFreq::G4, 4},
    {NoteFreq::FS4, 2},
    {NoteFreq::G4, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::REST, 8},
    {NoteFreq::REST, 0}};
constexpr Melody KrabMelody = {KrabNotes, 180};

constexpr Note PinkPantherNotes[] = {
    // Pink Panther theme
    // Score available at https://musescore.com/benedictsong/the-pink-panther
    // Theme by Masato Nakamura, arranged by Teddy Mason
    {NoteFreq::REST, 1},
    {NoteFreq::DS4, 8},
    {NoteFreq::E4, -4},
    {NoteFreq::REST, 8},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, -4},
    {NoteFreq::REST, 8},
    {NoteFreq::DS4, 8},
    {NoteFreq::E4, -8},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, -8},
    {NoteFreq::C5, 8},
    {NoteFreq::B4, -8},
    {NoteFreq::E4, 8},
    {NoteFreq::G4, -8},
    {NoteFreq::B4, 8},
    {NoteFreq::AS4, 2},
    {NoteFreq::A4, -16},
    {NoteFreq::G4, -16},
    {NoteFreq::E4, -16},
    {NoteFreq::D4, -16},
    {NoteFreq::E4, 2},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::DS4, 4},
    {NoteFreq::E4, -4},
    {NoteFreq::REST, 8},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, -4},
    {NoteFreq::REST, 8},
    {NoteFreq::DS4, 8},
    {NoteFreq::E4, -8},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, -8},
    {NoteFreq::C5, 8},
    {NoteFreq::B4, -8},
    {NoteFreq::G4, 8},
    {NoteFreq::B4, -8},
    {NoteFreq::E5, 8},
    {NoteFreq::DS5, 1},
    {NoteFreq::D5, 2},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 8},
    {NoteFreq::DS4, 8},
    {NoteFreq::E4, -4},
    {NoteFreq::REST, 8},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, -4},
    {NoteFreq::REST, 8},
    {NoteFreq::DS4, 8},
    {NoteFreq::E4, -8},
    {NoteFreq::FS4, 8},
    {NoteFreq::G4, -8},
    {NoteFreq::C5, 8},
    {NoteFreq::B4, -8},
    {NoteFreq::E4, 8},
    {NoteFreq::G4, -8},
    {NoteFreq::B4, 8},
    {NoteFreq::AS4, 2},
    {NoteFreq::A4, -16},
    {NoteFreq::G4, -16},
    {NoteFreq::E4, -16},
    {NoteFreq::D4, -16},
    {NoteFreq::E4, -4},
    {NoteFreq::REST, 4},
    {NoteFreq::REST, 4},
    {NoteFreq::E5, -8},
    {NoteFreq::D5, 8},
    {NoteFreq::B4, -8},
    {NoteFreq::A4, 8},
    {NoteFreq::G4, -8},
    {NoteFreq::E4, -8},
    {NoteFreq::AS4, 16},
    {NoteFreq::A4, -8},
    {NoteFreq::AS4, 16},
    {NoteFreq::A4, -8},
    {NoteFreq::AS4, 16},
    {NoteFreq::A4, -8},
    {NoteFreq::AS4, 16},
    {NoteFreq::A4, -8},
    {NoteFreq::G4, -16},
    {NoteFreq::E4, -16},
    {NoteFreq::D4, -16},
    {NoteFreq::E4, 16},
    {NoteFreq::E4, 16},
    {NoteFreq::E4, 2}};
constexpr Melody PinkPantherMelody = {PinkPantherNotes, 120};
